version: '3.9'
services:

  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
  
  documentupload:
    build: documentUpload
    ports:
      - "4004:4004"
    volumes:
      - ./documentUpload:/usr/app
      - /usr/app/node_modules
  
  event-bus:
    build: event-bus
    ports:
      - "4000:4000"
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  
  previouschats:
    build: previousChats
    ports:
      - "4001:4001"
    volumes:
      - ./previousChats:/usr/app
      - /usr/app/node_modules

  users:
    build: users
    ports:
      - "4002:4002"
    volumes:
      - ./users:/usr/app
      - /usr/app/node_modules